# Generated by Django 5.1.2 on 2024-11-04 12:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee_management_app', '0004_remove_employeedata_emp_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('proj_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proj_name', models.CharField(max_length=100, verbose_name='Project Name')),
                ('proj_requirement', models.TextField(verbose_name='Project Requirement')),
                ('proj_lead', models.CharField(max_length=100, verbose_name='Project Lead')),
                ('proj_manager', models.CharField(max_length=100, verbose_name='Project Manager')),
                ('proj_tech_stack', models.CharField(max_length=100, verbose_name='Project Tech Stack')),
                ('proj_status', models.CharField(max_length=100, verbose_name='Project Status')),
                ('proj_client_details', models.TextField(verbose_name='Client Details')),
                ('proj_estimate_date', models.DateTimeField()),
                ('proj_start_date', models.DateTimeField()),
                ('proj_end_date', models.DateTimeField()),
                ('proj_created', models.DateTimeField(auto_now_add=True)),
                ('proj_updated', models.DateTimeField(auto_now=True)),
                ('proj_business_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee_management_app.businessunit')),
            ],
        ),
    ]
