# Generated by Django 5.1.2 on 2024-10-21 05:15

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessUnit',
            fields=[
                ('bu_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bu_name', models.CharField(max_length=100, verbose_name='Business Unit Name')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=100, verbose_name='Department Name')),
                ('dept_head', models.CharField(max_length=100, verbose_name='Department Head')),
            ],
        ),
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('engagement_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('engagement_type', models.CharField(max_length=100, verbose_name='Engagement Type')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('skills_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('skills_name', models.CharField(max_length=100, verbose_name='Skill Name')),
            ],
        ),
        migrations.CreateModel(
            name='TechStack',
            fields=[
                ('techstack_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('techstack_name', models.CharField(max_length=100, verbose_name='Tech Stack Name')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeData',
            fields=[
                ('emp_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('emp_first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('emp_last_name', models.CharField(max_length=20, verbose_name='Last Name')),
                ('emp_personal_email', models.EmailField(max_length=254, unique=True)),
                ('emp_phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('emp_permanent_address', models.CharField(max_length=256)),
                ('emp_current_address', models.CharField(max_length=256)),
                ('emp_blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('N', 'Not Specified')], max_length=3)),
                ('emp_tech_group', models.CharField(max_length=100)),
                ('emp_date_of_joining', models.DateTimeField()),
                ('emp_dob', models.DateField()),
                ('emp_designation', models.CharField(max_length=100)),
                ('emp_years_of_experience', models.CharField(max_length=10)),
                ('emp_profile_photo', models.BinaryField(blank=True, null=True)),
                ('emp_ctc_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('emp_job_location', models.CharField(max_length=100)),
                ('emp_base_location', models.CharField(max_length=100)),
                ('emp_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('N', 'Not Specified')], max_length=1)),
                ('emp_allocation_status', models.CharField(choices=[('Allocated', 'Allocated'), ('Bench', 'Bench'), ('On Leave', 'On Leave')], max_length=100)),
                ('emp_location_hr', models.CharField(max_length=100)),
                ('emp_business_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee_management_app.businessunit')),
                ('emp_department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee_management_app.department')),
                ('emp_reporting_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportingManager', to='employee_management_app.employeedata')),
                ('emp_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to=settings.AUTH_USER_MODEL)),
                ('emp_type_of_engagement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee_management_app.engagement')),
                ('emp_skills', models.ManyToManyField(related_name='employees', to='employee_management_app.skill')),
                ('emp_tech_stacks', models.ManyToManyField(related_name='employees', to='employee_management_app.techstack')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeSkillRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_management_app.employeedata')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_management_app.skill')),
            ],
        ),
    ]
