# Generated by Django 5.1.2 on 2024-11-04 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management_app', '0003_employeeskillrelation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedata',
            name='emp_profile_photo',
        ),
    ]
