# Generated by Django 5.1.2 on 2024-11-04 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management_app', '0004_remove_employeedata_emp_profile_photo'),
        ('hr_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hruser',
            name='hr_personal_email_id',
            field=models.EmailField(default=1, editable=False, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hruser',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee_management_app.department'),
        ),
    ]
